# Generated by Django 6.0.3 on 2026-04-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyHydration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True, unique=True)),
                ("current_volume", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Workout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exercise_type", models.CharField(max_length=200)),
                ("sets", models.IntegerField()),
                ("reps", models.IntegerField()),
                ("date", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
