# Generated by Django 6.0.3 on 2026-04-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logger", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyhydration",
            name="goal_volume",
            field=models.IntegerField(default=2000),
        ),
    ]
